### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2 in SVGAndroidRenderer.java:2699

### ISSUE THREAD

**Issue by evgenynacu** [BigBadaboom/androidsvg#156] opened 2018-09-14 08:38 UTC
Exception while rendering SVG with specific arc:

         java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
             at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2699)
             at com.caverock.androidsvg.SVGAndroidRenderer.access$700(SVGAndroidRenderer.java:90)
             at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SVGAndroidRenderer.java:2561)
             at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SVG.java:2303)
             at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SVGAndroidRenderer.java:2518)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1065)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:343)
             at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:375)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:664)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:339)
             at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:375)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:664)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:339)
             at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:375)
             at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:621)
             at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:308)
             at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:436)
             at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:409)
             at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:346)

This happens for attached file [0026m.zip](https://github.com/BigBadaboom/androidsvg/files/2382584/0026m.zip)

Apparently, this is related to https://github.com/BigBadaboom/androidsvg/issues/62
float precision seems not to be enough. When I reversed this commit: https://github.com/BigBadaboom/androidsvg/commit/3e2aaceb9a5755a1ce3329657563cea26eb84568 error is gone and SVG is rendered correctly

**Comment by evgenynacu** [comment] 2018-09-14 08:39
Oh, sorry for the duplicate of https://github.com/BigBadaboom/androidsvg/issues/155
Had to put my findings there (about reverse patch)

**Comment by BigBadaboom** [comment] 2018-09-14 10:30
Thanks for the report.  It does seem to be a duplicate.

Marking as a duplicate of #155.

**Closed by BigBadaboom** 2018-09-14 10:30 UTC
Labels: duplicate
