### ISSUE TITLE
NullPointerException in Version 1.4

### ISSUE THREAD

**Issue by mueller-ma** [BigBadaboom/androidsvg#177] opened 2019-08-06 17:39 UTC
````
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.caverock.androidsvg.SVG$SvgContainer com.caverock.androidsvg.SVG$SvgObject.parent' on a null object reference
       at com.caverock.androidsvg.SVGParser.endElement + 1086(SVGParser.java:1086)
       at com.caverock.androidsvg.SVGParser.parseUsingXmlPullParser + 714(SVGParser.java:714)
       at com.caverock.androidsvg.SVGParser.parse + 603(SVGParser.java:603)
       at com.caverock.androidsvg.SVG.getFromInputStream + 150(SVG.java:150)
       at org.openhab.habdroid.util.ExtensionFuncsKt.toBitmap + 118(ExtensionFuncs.kt:118)
````

Version 1.4

Can you catch the NPE and re-throw as SVGParseException? I don't have the svg causing the issue.

**Comment by BigBadaboom** [comment] 2019-08-09 13:18
@mueller-ma I've been analysing the code trying to work out how this could have happened.  I'm not having much luck so far.  Can you provide any hints about the file or where it came from?

**Comment by mueller-ma** [comment] 2019-08-13 10:14
I don't know much about the svg. The app is the openHAB client.
Users can use any svg they want. It's downloaded from their webserver and parsed and shown in the app.
The client decides based on the mime type to parse the icon as bitmap or vector.

**Comment by BigBadaboom** [comment] 2019-08-13 11:27
Thanks. I'll keep looking.

**Comment by BigBadaboom** [comment] 2019-08-18 19:06
Fixed (sort of) for now.  Hopefully someone one day will teach us how this is supposed to happen. Bug in XmlPullParser??

**Comment by amanzan** [comment] 2019-10-17 15:53
Hello, I am having the same crash and don't know exactly why. Tried debugging and everything seems to be parsing correctly but I end up having the exception.

Uploading SVGs is not supported, but this is the URL where is hosted:
https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/523f/6176/489deb9b354d125115385c8f8c8c566a

**Comment by amanzan** [comment] 2019-10-17 16:13
Just to give more info, putting a try catch solves the issue and the SVG is displayed...but would like to know what is going on.

My log:
```

java.lang.NullPointerException: Attempt to read from field 'com.caverock.androidsvg.SVG$Box com.caverock.androidsvg.SVG$SvgViewBoxContainer.viewBox' on a null object reference
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:379)
        at com.caverock.androidsvg.SVGImageView.doRender(SVGImageView.java:355)
        at com.caverock.androidsvg.SVGImageView.setSVG(SVGImageView.java:142)
```

**Comment by BigBadaboom** [comment] 2019-10-17 17:51
Thanks @amanzan. Does that file reproduce the bug every time?

```
<svg width="94" height="1" viewBox="0 0 94 1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0.5H94" stroke="white"/>
</svg>

```

**Comment by amanzan** [comment] 2019-10-17 17:56
Yep, every time I try to draw that view, it crashes. It's inside a recyclerview and it's added dynamically, in case it helps

**Comment by BigBadaboom** [comment] 2019-10-17 18:25
Thanks vm.  I'll take a look.

**Comment by BigBadaboom** [comment] 2019-10-18 12:54
@amanzan I just created a test project with just an `SVGImageView` that loads your file.  Unfortunately I am not getting any exception.

Here's my test project, if you want to try it out yourself and see what happens.

[AndroidSVGIssue117.zip](https://github.com/BigBadaboom/androidsvg/files/3743914/AndroidSVGIssue117.zip)

Like  I think you suspect, I think there must be something else going on here.  Not just simply a parsing or rendering error.  You exception is happening in a totally different place than @mueller-ma.   It may be some sort of concurrency issue.

Would you be willing to share your project code with me?  Or a cut-down version of it that still fails?  I'm happy to sign an NDA if you wish.

**Comment by BigBadaboom** [comment] 2019-11-20 11:33
@amanzan Did you try the test app I posted?  Are you still getting the crash?

If so, can you provide more details of the device and android version etc?

If not I'll probably close this bug again.

**Closed** 2019-11-29 09:21 UTC
Labels: bug

**Comment by gowthami77** [comment] 2024-05-16 11:13
hi sir i am also facing the same issue can you please help me to resolve this 

 java.lang.NullPointerException: Attempt to read from field 'com.caverock.androidsvg.SVG$SvgContainer com.caverock.androidsvg.SVG$SvgObject.parent' on a null object reference
 com.caverock.androidsvg.SVGParser.endElement(SVGParser.java:1086)
com.caverock.androidsvg.SVGParser.parseUsingXmlPullParser(SVGParser.java:714)
com.caverock.androidsvg.SVGParser.parse(SVGParser.java:603)
com.caverock.androidsvg.SVG.getFromInputStream(SVG.java:150)
ai.supervue.hotels.ui.home.HomeFragment$1.onResponse(HomeFragment.java:97)
