### ISSUE TITLE
Make SVG.getRootElement public

### ISSUE THREAD

**Issue by sgallego** [BigBadaboom/androidsvg#243] opened 2021-12-14 16:03 UTC
Please,
make SVG.getRootElement public so we can access elements tree and manage it for other purposes, not only for rendering.
make public also SvgObject and its subclasses,

Thanks,

**Comment by BigBadaboom** [comment] 2021-12-15 07:06
Hi

This would happen as part of #130.  Are you asking for something different from what that issue proposes?

**Comment by sgallego** [comment] 2021-12-15 08:35
Hi,
I ask for something more simple, only to read SvgObject tree but, as you comment, this could be part of #130.
Thanks.

**Comment by BigBadaboom** [comment] 2021-12-15 11:53
Partial duplicate of #130

**Closed by BigBadaboom** 2021-12-15 11:53 UTC
Labels: duplicate

**Comment by BigBadaboom** [comment] 2021-12-15 11:59
Ok. I am going to mark this as a duplicate then.

If you need this urgently, there are a couple of ways you can do it yourself.

1. Fork the repo and implement the method yourself. Then use your custom build.
2. Use reflection to access that method, or the field it returns.  [Example here](https://www.geeksforgeeks.org/how-to-access-private-field-and-method-using-reflection-in-java/#:~:text=If%20we%20want%20to%20access,used%20to%20get%20private%20fields.)

I hope this is helpful for you until I get the chance to work on #130..

**Comment by sgallego** [comment] 2021-12-15 12:04
Hi,
I have tried 2, but I cannot do it because received objects are package private, so I cannot use them.
I have make a test with a fork and it works fine. I will do a pull request when I work more than for a test.
Thanks again.

**Comment by BigBadaboom** [comment] 2021-12-15 12:13
Hi

Thanks for offering a patch. But I probably wouldn't accept it.  I am reluctant to add a method that exposes internal objects, and will go away before very long.

I would prefer to wait until I can properly implement it as part of #130.
