### ISSUE TITLE
Stroke width and paint color

### ISSUE THREAD

**Issue by LevonVardanyan** [BigBadaboom/androidsvg#108] opened 2017-06-19 11:37 UTC
Can you add methods for changing parsed svg stroke width and color?

**Comment by BigBadaboom** [comment] 2017-06-19 14:11
For which element?  There will commonly be multiple elements in an SVG.

**Comment by LevonVardanyan** [comment] 2017-06-20 21:04
Below I paste svg which draws heart with stroke line. I Want to be able change color of stroke and width of stroke.  And one more question, can I scale svg before drawing on canvas.

`<?xml version="1.0" encoding="UTF-8"?>
<svg width="72px" height="72px" viewBox="0 0 72 72" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>heart</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Shapes" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="heart">
            <path d="M36,68.2926911 C33.0794135,65.3865159 30.0243735,62.7447428 24.9381935,58.5943308 C24.7400827,58.432669 22.2445774,56.400718 21.5175763,55.8057594 C14.1870479,49.8066487 10.1760474,46.0567802 6.84701502,41.6735684 C2.6485073,36.1455511 0.5,30.4621353 0.5,24.0007613 C0.5,4.48268871 23.1702743,-3.60636015 35.6216551,10.8050939 L35.9999926,11.2429886 L36.3783386,10.8051012 C48.8301777,-3.60632067 71.5,4.48263343 71.5,24.0007613 C71.5,30.4621353 69.3514927,36.1455511 65.152985,41.6735684 C61.8239526,46.0567802 57.8129521,49.8066487 50.4824237,55.8057594 C49.7554226,56.400718 47.2599173,58.432669 47.0618065,58.5943308 C41.9756265,62.7447428 38.9205865,65.3865159 36,68.2926911 Z"></path>
            <rect id="Rectangle" x="0" y="0" width="72" height="72"></rect>
        </g>
    </g>
</svg>`

**Comment by BigBadaboom** [comment] 2017-06-21 12:51
Okay. I think I can mark this as a duplicate of issue #11.  I will shortly be adding the ability to pass in additional CSS when rendering a file. Using this method, you will be able to override the styling of the elements in the SVG.

**Closed by BigBadaboom** 2017-06-21 12:51 UTC
Labels: duplicate, enhancement
