### ISSUE TITLE
Position of Rectf ignored when renderToCanvas

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#51] opened 2015-07-29 01:51 UTC
```
What steps will reproduce the problem?
1.Use renderToCanvas with a Rectf canv.renderToCanvas(svg,new 
RectF(dx,dy,width,height)

What is the expected output? What do you see instead?
The height and width of the image are correct but dx and dy are ignored.

What version of the product are you using? On what operating system?
v1.2.1


```

Original issue reported on code.google.com by `yannick....@math.uzh.ch` on 20 Jan 2015 at 7:56

**Comment by BigBadaboom** [comment] 2017-05-26 03:10
Same as bug #78.  Marking this as a duplicate of that one since it has more information.

**Closed by BigBadaboom** 2017-05-26 03:10 UTC
Labels: auto-migrated, bug, duplicate, Priority-Medium, Type-Defect
