### ISSUE TITLE
SVG renderToPicture not working with Oreo

### ISSUE THREAD

**Issue by initiuminc1** [BigBadaboom/androidsvg#163] opened 2019-01-04 11:36 UTC
I have the issue with devices above oreo. Working well with the other devices

**Comment by BigBadaboom** [comment] 2019-01-04 13:04
Thanks for your report.  Do you have any other information?  Do you get any errors?

**Comment by initiuminc1** [comment] 2019-04-11 09:41
Not getting any specific errors. instead of that getting an empty white screen. The same code works well on M

**Comment by BigBadaboom** [comment] 2019-04-11 11:13
Can you provide a sample of code?  Or perhaps a test project or APK?

**Comment by BigBadaboom** [comment] 2019-05-21 08:39
Cannot reproduce.

Closing for now. If you can provide an example that fails, please update the issue and I will reopen it.

**Closed by BigBadaboom** 2019-05-21 08:39 UTC
