### ISSUE TITLE
viewBox not used, header need width and height

### ISSUE THREAD

**Issue by gvollant** [BigBadaboom/androidsvg#128] opened 2018-02-01 09:18 UTC
Adobe illustrator generate SVG with viewBox in header, but not width and height

[svg_showbug.zip](https://github.com/BigBadaboom/androidsvg/files/1684841/svg_showbug.zip)

beginning of SVG generated by adobe illustrator : 

`<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">`

I need manuallly add height and width parameter in svg markup to be compatible with the androidsvg library.
In this sample, I just add `height="512" width="512" ` after `viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" `

`<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" height="512" width="512" xml:space="preserve">`

**Comment by BigBadaboom** [comment] 2018-02-01 15:58
Hi. Thanks for the report.  Which version of AndroidSVG are you using?

**Comment by gvollant** [comment] 2018-02-02 11:37
I tried with latest from github

**Comment by BigBadaboom** [comment] 2018-02-02 12:04
If you pulled the code more than three of days ago, then please try again. I fixed an issue on Jan 29 that affected viewport calculation. It's possible that might be the cause.

If not, I will look into it, as soon as I have a free moment.

**Comment by gvollant** [comment] 2018-02-02 13:22
I downloaded 1 feb 18.

Just try with the content of svf_showbug.zip I uploaded on first message. Only one svg displayed with android svg, other viewer display both

**Comment by BigBadaboom** [comment] 2018-02-02 13:54
Ok. Thanks. I will take a look.

**Comment by BigBadaboom** [comment] 2018-02-02 19:02
I have tried your test file, and it worked as expected in my test app.  So can you provide more details about how you are rendering the file?  Are you rendering it yourself to a Canvas? Or are you using an ImageView or SVGImageView?  Can you post some code and/or the relevant section of your layout XML please?

If you are using an ImageView, are you perhaps striking the problem described in the last section of the FAQ? http://bigbadaboom.github.io/androidsvg/faq.html#ScaleType_.CENTER_doesn't_work_when_using_an_ImageView_or_S

**Comment by gvollant** [comment] 2018-02-03 07:35
here is my code
`
    public static Bitmap buildBitmapFromSvg(android.content.Context context,int res_id,int width,int height)
    {
        if (res_id == 0)
            return null;

        try

        {
            SVG svg = SVG.getFromResource(context, res_id);

            // Set the viewBox attribute using the document's width and height
            svg.setDocumentViewBox(0, 0, svg.getDocumentWidth(),
                    svg.getDocumentHeight());

// Now set width and height to 100% so it will scale to fit the canvas
            svg.setDocumentWidth("100%");
            svg.setDocumentHeight("100%");

            //android.content.res.Resources resources = convertView.getContext().getResources();


            //Bitmap maskImage = BitmapFactory.decodeResource(resources, R.drawable.ic_buttons_plus);
            Canvas canvas = new Canvas();
            Bitmap solidImage = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            solidImage.eraseColor(Color.TRANSPARENT);

            Bitmap mainImage = solidImage;//get original image

            Bitmap result = Bitmap.createBitmap(mainImage.getWidth(), mainImage.getHeight(), Bitmap.Config.ARGB_8888);

            canvas.setBitmap(result);
            Paint paint = new Paint();


            canvas.drawBitmap(mainImage, 0, 0, paint);

            canvas.drawPicture(svg.renderToPicture(canvas.getWidth(), canvas.getHeight()));



            return result;
        } catch (SVGParseException e) {
            return null;
        }

    }

    public static Bitmap buildBitmapFromSvg(android.content.Context context,int res_id,int color,int width,int height)
    {
        if (res_id == 0)
            return null;

        try

        {
            SVG svg = SVG.getFromResource(context, res_id);

            // Set the viewBox attribute using the document's width and height
            svg.setDocumentViewBox(0, 0, svg.getDocumentWidth(),
                    svg.getDocumentHeight());

// Now set width and height to 100% so it will scale to fit the canvas
            svg.setDocumentWidth("100%");
            svg.setDocumentHeight("100%");

            //android.content.res.Resources resources = convertView.getContext().getResources();


            //Bitmap maskImage = BitmapFactory.decodeResource(resources, R.drawable.ic_buttons_plus);
            Canvas canvas = new Canvas();
            Bitmap solidImage = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            solidImage.eraseColor(Color.TRANSPARENT);

            Bitmap mainImage = solidImage;//get original image

            Bitmap result = Bitmap.createBitmap(mainImage.getWidth(), mainImage.getHeight(), Bitmap.Config.ARGB_8888);

            canvas.setBitmap(result);
            Paint paint = new Paint();


            canvas.drawBitmap(mainImage, 0, 0, paint);

            canvas.drawPicture(svg.renderToPicture(canvas.getWidth(), canvas.getHeight()));


            result=ApplyColorToBitmap(result, color);
            return result;
        } catch (SVGParseException e) {
            return null;
        }

    }
`

**Comment by gvollant** [comment] 2018-02-03 07:44
I fixed my code by using now


`
            float documentWidth=svg.getDocumentWidth();
            float documentHeight=svg.getDocumentHeight();
            if ((documentWidth>0) && (documentHeight>0)) {
                // Set the viewBox attribute using the document's width and height
                svg.setDocumentViewBox(0, 0, svg.getDocumentWidth(),
                        svg.getDocumentHeight());
            }
`


instead

`
        // Set the viewBox attribute using the document's width and height
        svg.setDocumentViewBox(0, 0, svg.getDocumentWidth(),
                svg.getDocumentHeight());`

**Comment by BigBadaboom** [comment] 2018-02-03 09:37
You seem to be overwriting the `viewBox` every time, which will often result in the SVG being rendered incorrectly.  The `viewBox` is very important because it tells the render what the size of the contents is.  If you provide a bad `viewBox`, the file will render incorrectly.

If you are trying to add a `viewBox` to all SVGs that don't have one, then you probably want to check that the `viewBox` is missing before add one:

```
if (svg.getDocumentViewBox() == null)
{
  // SVG is missing a viewBox. Can we make one from the width and height?
  float documentWidth = svg.getDocumentWidth();
  float documentHeight = svg.getDocumentHeight();
  if ((documentWidth>0) && (documentHeight>0))
  {
    // Set the viewBox attribute using the document's width and height
    svg.setDocumentViewBox(0, 0, documentWidth, documentHeight);
  }
  // else there is nothing we can do about it
}
```

Hope this helps.

Is your problem resolved now?  Can I close this issue?

**Comment by BigBadaboom** [comment] 2018-02-05 07:02
I am going to close this bug on the assumption that your problem is now resolved.
If I am wrong, let me know and I will reopen.

**Closed by BigBadaboom** 2018-02-05 07:02 UTC
Labels: bug
