### ISSUE TITLE
Some Adobe Illustrator files wont render at all (see example)

### ISSUE THREAD

**Issue by frmz** [BigBadaboom/androidsvg#98] opened 2016-07-18 11:07 UTC
Hi! Thanks for developing such a great library. I just wanted to report that the attached file (created from Adobe Illustrator) won't open at all in 1.2.2 beta, parser returns an XML exception (i had to change SVG extension into TXT to allow upload here).

[hex.txt](https://github.com/BigBadaboom/androidsvg/files/368853/hex.txt)

**Comment by BigBadaboom** [comment] 2016-07-18 11:20
What is the exception you are getting?  Please post the details.

**Comment by frmz** [comment] 2016-07-20 14:49
I tested it again and, not sure why, i cant get any exception now, i just get an empty bitmap as a result but full path is decoded. Probably its using a feature that is not yet implemented?

**Comment by BigBadaboom** [comment] 2016-07-20 15:00
AndroidSVG *does* handle bitmap images that are embedded as Base64 DataURIs, which is what is happening in your SVG.  So in theory it should be working.

It's possible there is some other problem related to this particular file. For example, your embedded image is very large.  The attribute value containing the encoded image is well over 200k characters.  I don't think I ever tested the lib with a DataURI that large.

When I get some free time, I will try out your file and see if I can work out what is going on.

The bitmap in your SVG file is nearly 800x800 pixels.  If you are not displaying your SVG as large as that on your device, then you might try exporting your SVG with a lower DPI so that your image file size is smaller.  That may work better.  But that's just a guess.

**Comment by frmz** [comment] 2016-07-21 07:47
@BigBadaboom thanks! so my apps allows the users to load their own SVGs so i have no control over the files and i just wanted to highlight that this specific one didn't work, i am not getting many reports on non working SVGs so its not a big issue, i also can confirm that this is not a memory issue, parsing goes through (even if it takes a while) without any issue but returned Picture simply does not show anything

**Comment by BigBadaboom** [comment] 2017-05-24 08:13
@frmz I finally got a chance to look at this issue.  I was unable to reproduce this problem on Android 7.1.2.  I believe there have been recent changes to Android's XML parser, so perhaps this issue with long attribute values has been resolved.  Assuming that's the case, there probably isn't much I could do to fix this on older versions of Android anyway (other than switching to a third-party XML parser.

Is this is still an issue you are striking?  If so, can you provide more details of the devices and Android versions that you are seeing on. That would be helpful.

Otherwise I will likely just close it as "works for me".

**Comment by frmz** [comment] 2017-05-24 12:49
Didnt have any report of this issue since a few months so from my side even if its still there impact is low, might be related to some Android release or specific combo, i confirm that i cant reproduce on latest 7.x either

**Comment by BigBadaboom** [comment] 2017-05-24 13:01
Thanks. I will close it then.

**Closed by BigBadaboom** 2017-05-24 13:01 UTC
Labels: bug, wont fix, works for me
