### ISSUE TITLE
NullPointerException in 1.2.2-beta1 when parsing SVG document

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#59] opened 2015-07-29 01:51 UTC
```
What steps will reproduce the problem?
1. Parse a SVG document (from a String, but I don't think this matters)
2. Receive a NullPointerException
3.

What is the expected output? What do you see instead?
Version 1.2.1 parses this same SVG document fine. On version 1.2.2-beta1 (with 
the same exact SVG), I get a NPE;
java.lang.NullPointerException
at com.caverock.androidsvg.SVGParser.parseFont(SVGParser.java:3253)
at com.caverock.androidsvg.SVGParser.processStyleProperty(SVGParser.java:2478)
at com.caverock.androidsvg.SVGParser.parseAttributesStyle(SVGParser.java:2363)
at com.caverock.androidsvg.SVGParser.text(SVGParser.java:1238)
at com.caverock.androidsvg.SVGParser.startElement(SVGParser.java:470)
at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:394)
at com.caverock.androidsvg.SVG.getFromString(SVG.java:158)

What version of the product are you using? On what operating system?
1.2.2-beta1 on Android (I tried this on 4.4.4 and 5.1).

Please provide any additional information below.
The SVG document is not publicly available, but I can get you the String for it 
if required.

```

Original issue reported on code.google.com by `m...@marcbernstein.info` on 30 Apr 2015 at 7:53

**Comment by BigBadaboom** [comment] 2016-02-04 16:48
I am not able to reproduce this now.  It looks like this problem was fixed by a patch applied after the 1.2.2-beta1 release.

Marking Fixed.

**Closed** 2016-02-04 16:48 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
