### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hellaandrew** [BigBadaboom/androidsvg#155] opened 2018-09-08 21:34 UTC
I have encountered this exception with your library, which is pretty great, by the way.

Line of code that throws:
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2699)

Full stacktrace:
W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2699)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.access$700(SVGAndroidRenderer.java:90)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SVGAndroidRenderer.java:2561)
W/System.err:     at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SVG.java:2303)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SVGAndroidRenderer.java:2518)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1065)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:343)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:375)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:621)
W/System.err:     at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:308)
W/System.err:     at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:536)
W/System.err:     at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:490)
------- My code -------
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

For your reference, here is the svg data I am trying to parse so you can test.
[Zip of SVG](https://www.dropbox.com/s/jmn32faj5mcb7sz/test_svg.zip?dl=0)

**Comment by BigBadaboom** [comment] 2018-09-09 03:59
Thanks very much for the bug report.  I will check it out shortly.

**Comment by BigBadaboom** [comment] 2018-09-14 10:31
Issue #156 has been marked as a duplicate of this issue.  See #156 for another test file.

**Comment by BigBadaboom** [comment] 2018-09-14 10:32
Interesting that after all this time, two people strike the same error within a week of each other.  Which version of Android were you testing on?  I wonder if there is a change in Android P that has triggered this.

I suspect it is going to be interesting task to find a fix that (a)  solves this, and (b) doesn't result in a regression of #62.

**Comment by hellaandrew** [comment] 2018-09-14 18:36
Confirmed the same issue happens on a device running Lollipop.

**Comment by BigBadaboom** [comment] 2018-09-15 05:43
Thanks for the extra testing.

**Comment by evgenynacu** [comment] 2018-09-15 20:34
I got this exception on Android 8.1. I think this one depends on arc parameters (because of overflow in float)

**Comment by BigBadaboom** [comment] 2018-09-23 10:48
Fixed.

Switched back to doubles, and added a check around the `Math.acos()` call so we can hopefully avoid, or mitigate the issue #62 problem, if it still exists.  Unfortunately I don't have a copy of the original test file from that bug to test with.

**Comment by hellaandrew** [comment] 2018-09-23 20:36
Awesome. Thanks for this man!

**Comment by przemyslaw-sf** [comment] 2018-10-09 15:50
@BigBadaboom It is possible to release new version with this fix?

**Comment by BigBadaboom** [comment] 2018-10-10 12:04
@przemyslaw-sf Closer to the release of 1.4, I will likely start releasing snapshots.  But in the meantime it is fairly easy to clone and build yourself.

**Comment by KravaDanil** [comment] 2019-07-11 20:30
Still reproducible on 1.4 
`    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
        at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2730)
        at com.caverock.androidsvg.SVGAndroidRenderer.access$700(SVGAndroidRenderer.java:89)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SVGAndroidRenderer.java:2584)
        at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SVG.java:2311)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SVGAndroidRenderer.java:2541)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1082)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:348)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:625)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:313)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:440)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:413)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:350)`

with this svg file:
[f06a2b6b-ab23-4d12-abc6-e4a0cb4f30c3.zip](https://github.com/BigBadaboom/androidsvg/files/3383832/f06a2b6b-ab23-4d12-abc6-e4a0cb4f30c3.zip)

**Comment by BigBadaboom** [comment] 2019-07-13 18:57
Closing again :)  This is a slightly different issue which I will fix under the original ticket #176.

**Closed by BigBadaboom** 2019-07-13 18:57 UTC
Labels: bug
