### ISSUE TITLE
Crashes Proguard

### ISSUE THREAD

**Issue by ScottPierce** [BigBadaboom/androidsvg#114] opened 2017-08-15 03:20 UTC
**Problem:**
I'm getting the following error for Android SVG when using proguard:

```
Warning: com.caverock.androidsvg.SVGImageView: can't find referenced class com.caverock.androidsvg.R$styleable
Warning: com.caverock.androidsvg.SVGImageView: can't find referenced class com.caverock.androidsvg.R$styleable
Warning: com.caverock.androidsvg.SVGImageView: can't find referenced class com.caverock.androidsvg.R
```

Using the following configuration fixes the issue:
```
-dontwarn com.caverock.androidsvg.**
```

**Request:**
It'd be nice if there was a recommended proguard config. I believe they can even be packaged with android libraries so that your users wouldn't even have to think about it, but would automatically be imported.

**Comment by BigBadaboom** [comment] 2017-08-15 05:42
> It'd be nice if there was a recommended proguard config.

I definitely agree.  I need to look into ProGuard for libraries and see what I can do to help out library users with this.

Pretty much every method in the library needs to be kept.  Except perhaps the SVGImageView and SVGExternalFileResolver, if you are not using those.  AndroidSVG currently uses some reflection in the CSS processor, so I think there are some issues if you use obfuscation.  Use of reflection will be removed in the next release.

**Comment by M-Khay** [comment] 2018-02-26 18:38
any updates on the proguard-rules for using this library . I'm getting an error as below only on my release build not on dev build

FATAL EXCEPTION: AsyncTask #4
                                                                             java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                 at java.lang.Thread.run(Thread.java:856)
                                                                              Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.access$700(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.render(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVG.renderToPicture(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVG.renderToPicture(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGImageView$LoadAssetTask.doInBackground(Unknown Source)
                                                                                 at com.caverock.androidsvg.SVGImageView$LoadAssetTask.doInBackground(Unknown Source)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:234)

**Comment by BigBadaboom** [comment] 2018-02-26 18:51
I'm not a Proguard expert, but pretty much everything in the library is needed, so perhaps try:

    -keep class com.caverock.** { *; }

**Comment by M-Khay** [comment] 2018-02-26 19:01
I tried it, didn't work out for me. I'm still on the issue, will post something useful once I find a solution.

**Comment by BigBadaboom** [comment] 2018-02-26 19:04
Thank you.  It is on my list of things to fix for the 1.3 release.  But I haven't had a chance to investigate it yet, sorry.

**Comment by devemux86** [comment] 2018-02-26 19:18
FYI
All these years we use AndroidSVG parser in [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm) vector map libraries, the following generic ProGuard rules usually work for most third-party libraries:
```groovy
-keep class com.** { *; }
-dontwarn com.**
-keep class org.** { *; }
-dontwarn org.**
```

**Comment by BigBadaboom** [comment] 2018-08-20 07:02
Release 1.3 seems to work fine without any special ProGuard rules.

I didn't get the warnings that @ScottPierce reported.

After the fix for issue #61, the only code left that uses reflection is either inconsequential logging statements, and some code that is unaffected by obfuscation.

Is anyone still getting Proguard errors or warnings with 1.3?

**Comment by kaychyka17** [comment] 2018-08-21 06:31
@BigBadaboom with Release 1.3 it works for me 👍  (Maybe you should add Release 1.3 under releases tab? :) )

**Comment by BigBadaboom** [comment] 2018-08-25 15:39
Ok then. Marking fixed on the assumption all is good.

**Closed by BigBadaboom** 2018-08-25 15:39 UTC
Labels: enhancement

**Comment by JohanDufau** [comment] 2018-11-23 10:15
Hello, I still have the issue with v1.3 of the lib and API 28.
The fix in my proguard-rules.pro works for me:
```
-dontwarn com.caverock.androidsvg.**
```

I think it should be added in the Readme :)

**Comment by BigBadaboom** [comment] 2018-11-28 11:09
Hi @JohanDufau. Thanks for the followup.

What errors were you getting?  Can you supply any further details?  Eg. the rest of your proguard file

**Comment by Vall0n** [comment] 2019-03-04 10:38
Hi, I got this issue: Warning: com.caverock.androidsvg.SVGAndroidRenderer: can't find referenced method 'int save(int)' in library class android.graphics.Canvas. But as @JohanDufau pointed out the 

> -dontwarn com.caverock.androidsvg.** 

does the job. I used the proguard-android-optimize.txt

**Comment by BigBadaboom** [comment] 2019-03-04 10:48
@Vall0n Your issue is a little different I think.  Yours is likely issue #148.

**Comment by Vall0n** [comment] 2019-03-04 10:58
@BigBadaboom K, thanks for the fast response!
