### ISSUE TITLE
Scale type of imageView is not working correctly

### ISSUE THREAD

**Issue by siralam** [BigBadaboom/androidsvg#123] opened 2018-01-17 05:13 UTC
Hi!

I used [your suggested method here](http://bigbadaboom.github.io/androidsvg/use_with_ImageView.html) to load SVG into my imageView.

The image can be shown with correct aspect ratio, and complete rendering;  
However the scale type seems to be incorrect.  

What I encountered:  
1. If I do not set scaleType (i.e. fitCenter), the image is located in the center of the view, but leaving a lot of empty padding to the view's edges.  
2. If I set the scaleType to be "fitXY", the image is located in the left bottom corner with a large part of it cropped, leaving top and right hand side of the view empty.

Do you have any suggestion for correctly handling the scale type? The ultimate goal I want is to let the SVG fill up the ImageView.

My SVG does have a viewBox:
```xml
<svg id="GF-map" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2176 924">
```

And I have also tried the below:
```java
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");
```
But the image becomes even smaller, no matter what scaleType I set.

**Comment by BigBadaboom** [comment] 2018-01-17 07:05
Try giving your SVG a specific `width` and `height`.  The values from the `viewBox` should work.  For example.

    <svg id="GF-map" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2176 924"
         width="2176" height="924">

If the SVG has no `width` and `height` attributes, then AndroidSVG will end up using a default width and height of 512. This default square viewPort is what will be causing your confusing padding issues.

**Comment by siralam** [comment] 2018-01-17 07:20
@BigBadaboom Thanks for your prompt reply! I tried adding width and height to the SVG file, but it has no effect.

On the other hand, I altered the container of the `ImageView` to have the same aspect ratio as the SVG file. Now, if I do not set any scale type (i.e. fitCenter), the image almost rendered perfectly, except that it still has a little padding (top and bottom around 2dp; left and right around 4dp) to the edges.

**Comment by BigBadaboom** [comment] 2018-01-17 07:39
> I tried adding width and height to the SVG file, but it has no effect.

Setting the width and height *should* mean that scaleType starts behaving more sensibly.

**Comment by BigBadaboom** [comment] 2018-01-17 07:46
> I tried adding width and height to the SVG file, but it has no effect.

Setting the SVG `width` and `height` should result in `scaleType` behaving more sensibly.  For example `fitXY` stretching the SVG to match the bounds of the imageView.

> it still has a little padding (top and bottom around 2dp; left and right around 4dp) to the edges.

To things to check:

1. check that the ImageView has no layout padding set.
2. that there is no padding around the SVG contents due to the `viewBox`

**Comment by siralam** [comment] 2018-01-17 07:52
> Setting the SVG width and height should result in scaleType behaving more sensibly. For example fitXY stretching the SVG to match the bounds of the imageView.

Sadly, setting scaleType to "fitXY" still makes the image very small and locate itself on the top left hand corner.

> check that the ImageView has no layout padding set.
No padding was set in ImageView.  

> that there is no padding around the SVG contents due to the viewBox
I am not 100% sure about this one, but if I open the SVG using macOS 's preview or using Chrome, both render the image to the edge of the viewport. So I think there should not be any intrinsic padding from the SVG.

Moreover, I found that setting scaleType to centerCrop solves the problem. But why?

**Comment by BigBadaboom** [comment] 2018-01-17 08:10
> I found that setting scaleType to centerCrop solves the problem. But why?

centerCrop scales the image so that it fills the view, allowing it to overflow vertically or horizontally, if necessary, to achieve that.

I'm not sure why you are having so many problems.  I'll experiment and see if I can reproduce it myself.   Can you send me your layout file and SVG perhaps?  You can send them to me directly at androidsvgfeedback@gmail.com if you don't want to attach them to a public bug report.

**Comment by BigBadaboom** [comment] 2018-01-18 08:43
This is a duplicate of issue #79.

**Comment by BigBadaboom** [comment] 2018-01-18 08:46
I've done some investigating and discovered that `fitXY` and `center` do not seem to work for PictureDrawables.  I haven't found any workaround, and I don't think there is any way that I can solve the problem by altering AndroidSVG.

If you are intereted in seeing it fixed, star the following Android bug report:
https://issuetracker.google.com/issues/72137551

**Comment by BigBadaboom** [comment] 2018-01-18 08:46
Marking closed: dupicate.

**Closed by BigBadaboom** 2018-01-18 08:46 UTC
Labels: duplicate
