### ISSUE TITLE
Repated renderToCanvas upscales result

### ISSUE THREAD

**Issue by jbruchanov** [BigBadaboom/androidsvg#75] opened 2015-10-27 18:00 UTC
I have this code
```java
SVG svg = mSVGs[index];
if (svg == null) {
    svg = mSVGs[index] = SVG.getFromResource(getResources(), mImages[index]);
}
if (mBitmap == null) {
    RectF box = svg.getDocumentViewBox();
    svg.setDocumentViewBox(0, 0, box.width(), box.height());
    mBitmap = Bitmap.createBitmap((int) Math.ceil(box.width()), (int) Math.ceil(box.height()), Bitmap.Config.ARGB_4444);
    mBitmapDrawable = new BitmapDrawable(mBitmap);
    mImageView.setImageDrawable(new BitmapDrawable(mBitmap));
    mCanvas = new Canvas(mBitmap);
}
mCanvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.MULTIPLY);
svg.renderToCanvas(mCanvas);
mImageView.invalidate();
```

running it in "loop" to create animation seems that image is upscaling a little so after few iterations you can easily see it's upscaled...

**Comment by jbruchanov** [comment] 2015-10-27 18:13
seems that creating canvas every call helps...

**Comment by BigBadaboom** [comment] 2015-10-28 00:42
It's not clear what you mean.  Do you mean it slowly gets bigger and bigger?

I suppose it is possible that AndroidSVG is not restoring the current Canvas transform on exit, but I thought that was tested.  What happens if you put a `save()` and `restore()` surrounding your render?

    mCanvas.save();
    svg.renderToCanvas(mCanvas);
    mCanvas.restore();

I noticed also that there seems to be a bug in your code.  This line is probably unnecessary:

    svg.setDocumentViewBox(0, 0, box.width(), box.height());

This is resetting the viewBox `x` and `y` values.  If they are not zero in the original SVG, this would have the effect of causing the SVG to be rendered in the wrong place.

**Comment by jbruchanov** [comment] 2015-10-28 09:57
@BigBadaboom 
oh sorry for confusing description 
```
mCanvas.save();
svg.renderToCanvas(mCanvas);
mCanvas.restore();
```
**helps** => seems your canvas matrix operations are not getting reset on ```renderToCanvas``` leaving

true about
```
svg.setDocumentViewBox(0, 0, box.width(), box.height());
```
it's not necessary for the example (doesn't have influence for the issue) I was testing just something with viewBox and didn't clean the code fully before posting

**Comment by BigBadaboom** [comment] 2015-10-28 14:33
This is a duplicate of Issue #50

**Closed** 2015-10-28 14:33 UTC
Labels: bug, Type-Defect
