### ISSUE TITLE
I want to get only drawn content of svg as picture 

### ISSUE THREAD

**Issue by Keyurshingala** [BigBadaboom/androidsvg#273] opened 2023-08-29 15:03 UTC

**Comment by BigBadaboom** [comment] 2023-08-30 23:04
Can you explain more about what you are trying to do please?

**Comment by Keyurshingala** [comment] 2023-09-06 06:10
> Can you explain more about what you are trying to do please?

explained in #274

**Comment by BigBadaboom** [comment] 2023-09-07 04:03
Duplicate of #274. Closing.

**Closed by BigBadaboom** 2023-09-07 04:03 UTC
Labels: question
