### ISSUE TITLE
Scale in ImageView

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#40] opened 2015-07-29 01:51 UTC
```
SVGImageView doesn't properly scale the image. Even if w o h are changed, it 
seems that only takes w and preserves aspect ratio


SVGImageView siv = new SVGImageView(this);
siv.setImageResource(R.drawable.image_svg);

int w=100;
int h=100;

RelativeLayout.LayoutParams rllp = new RelativeLayout.LayoutParams(w,h);
siv.setLayoutParams(rllp);


```

Original issue reported on code.google.com by `thaedne...@gmail.com` on 7 Jul 2014 at 10:06

Attachments:
- [image_svg.svg](https://storage.googleapis.com/google-code-attachments/androidsvg/issue-40/comment-0/image_svg.svg)

**Comment by BigBadaboom** [comment] 2018-01-18 09:08
Duplicate of issue #79 and #123.

Marking closed: duplicate, bug in android.

**Closed by BigBadaboom** 2018-01-18 09:08 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated, bug, bug in android, duplicate
