### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by MisterY** [BigBadaboom/androidsvg#117] opened 2017-09-22 21:59 UTC
> src\main\java\com\caverock\androidsvg\SVGAndroidRenderer.java uses or overrides a deprecated API.

Getting the above error recently, when compiling.
From what I see,

    canvas.saveLayerAlpha 
and 

    canvas.save(Canvas.MATRIX_SAVE_FLAG);
are marked as deprecated.

**Comment by devemux86** [comment] 2017-09-23 08:54
Wouldn't call it an error, it's the usual deprecations with each Android version.

Using new method with a check `Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP` to fallback to old method for supporting every Android version could work.

**Comment by MisterY** [comment] 2017-09-23 12:45
Yes, true. My main problem was that the build would not complete and these were the only reported errors in the process. Removing minification solved it, whatever the real reason was.

So, this item can serve as a reminder to update the deprecation headers as the platform moves on.

**Comment by BigBadaboom** [comment] 2017-09-29 14:39
Avoiding the use of those deprecated methods will require a rewrite of how AndroidSVG implements some features.  I'll probably have to do that sooner rather than later anyway as there is a demand for SVGImageView to be render directly so that it is hardware accelerated... :-/

**Comment by BigBadaboom** [comment] 2017-12-11 14:00
Marking as duplicate of issue #45 since that call is used in the mask handling code.

**Closed by BigBadaboom** 2017-12-11 14:00 UTC
Labels: duplicate
