### ISSUE TITLE
below svg is getting cut in imageview,  I want to get whole svg as picture how to do it

### ISSUE THREAD

**Issue by Keyurshingala** [BigBadaboom/androidsvg#274] opened 2023-08-29 15:04 UTC
https://drive.google.com/file/d/1zeiUjavyeTYR08hC-eK0NmTo7x-BycJJ/view?usp=drive_link
#273 

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" id="canvas" viewBox="0 0 500 500" width="500" height="500">
    <g id="shape_group_0_1" transform="translate(-20, 0) scale(1.166) rotate(0)">
        <path id="0_1A" d="M0,0 l60,-60  l60,60  l-60,60  l-60,-60z" fill="#264551" />
        <path id="0_1B" d="M0,0 h120  l-60,60  l-60,-60z" fill="#223E48" />
        <g id="0_1C_icon" transform="translate(44.5, -38.5) scale(0.96875)" color="#ffffff">
            <g>
                <path
                    d="M14.615 4.928c.487-.986 1.284-.986 1.77 0l2.25 4.554c.486.986 1.775 1.923 2.864 2.08l5.023.73c1.09.16 1.335.917.547 1.685l-3.636 3.544c-.788.77-1.28 2.284-1.095 3.37l.858 5.003c.186 1.085-.46 1.553-1.433 1.04l-4.495-2.362c-.974-.51-2.567-.51-3.54 0l-4.496 2.364c-.974.512-1.618.044-1.432-1.04l.858-5.005c.186-1.086-.307-2.6-1.094-3.37L3.93 13.978c-.788-.768-.542-1.525.547-1.684l5.026-.73c1.088-.158 2.377-1.095 2.864-2.08l2.248-4.555z"
                    fill="currentColor" />
            </g>
        </g>
        <g id="0_1D" fill="#ffffff">
            <text id="title_0_1D_line_0" x="60.0" y="13.0" font-size="7.0" font-weight="normal"
                fill="#ffffff" text-anchor="middle" font-family="OpenSans">Designated Space
            </text>
        </g>
    </g>
    <g id="shape_group_1_1" transform="translate(75, -45) scale(0.75) rotate(0)">
        <path id="1_1A" d="M0,0 l60,-60  l60,60  l-60,60  l-60,-60z" fill="#479E8B" />
        <path id="1_1B" d="M0,0 h120  l-60,60  l-60,-60z" fill="#3F8E7D" />
        <g id="1_1C_icon" transform="translate(44.5, -38.5) scale(0.96875)" color="#ffffff">
            <g>
                <path
                    d="M14.615 4.928c.487-.986 1.284-.986 1.77 0l2.25 4.554c.486.986 1.775 1.923 2.864 2.08l5.023.73c1.09.16 1.335.917.547 1.685l-3.636 3.544c-.788.77-1.28 2.284-1.095 3.37l.858 5.003c.186 1.085-.46 1.553-1.433 1.04l-4.495-2.362c-.974-.51-2.567-.51-3.54 0l-4.496 2.364c-.974.512-1.618.044-1.432-1.04l.858-5.005c.186-1.086-.307-2.6-1.094-3.37L3.93 13.978c-.788-.768-.542-1.525.547-1.684l5.026-.73c1.088-.158 2.377-1.095 2.864-2.08l2.248-4.555z"
                    fill="currentColor" />
            </g>
        </g>
        <g id="1_1D" fill="#ffffff">
            <text id="title_1_1D_line_0" x="60.0" y="13.0" font-size="7.0" font-weight="normal"
                fill="#ffffff" text-anchor="middle" font-family="OpenSans">Organize and
            </text>
            <text id="title_1_1D_line_1" x="60.0" y="21.4" font-size="7.0" font-weight="normal"
                fill="#ffffff" text-anchor="middle" font-family="OpenSans">Categorize
            </text>
        </g>
    </g>
    <g id="shape_group_2_1" transform="translate(90, 30) scale(1) rotate(0)">
        <path id="2_1A" d="M0,0 l60,-60  l60,60  l-60,60  l-60,-60z" fill="#E9C463" />
        <path id="2_1B" d="M0,0 h120  l-60,60  l-60,-60z" fill="#D1B059" />
        <g id="2_1C_icon" transform="translate(44.5, -38.5) scale(0.96875)" color="#ffffff">
            <g>
                <path
                    d="M14.615 4.928c.487-.986 1.284-.986 1.77 0l2.25 4.554c.486.986 1.775 1.923 2.864 2.08l5.023.73c1.09.16 1.335.917.547 1.685l-3.636 3.544c-.788.77-1.28 2.284-1.095 3.37l.858 5.003c.186 1.085-.46 1.553-1.433 1.04l-4.495-2.362c-.974-.51-2.567-.51-3.54 0l-4.496 2.364c-.974.512-1.618.044-1.432-1.04l.858-5.005c.186-1.086-.307-2.6-1.094-3.37L3.93 13.978c-.788-.768-.542-1.525.547-1.684l5.026-.73c1.088-.158 2.377-1.095 2.864-2.08l2.248-4.555z"
                    fill="currentColor" />
            </g>
        </g>
        <g id="2_1D" fill="#ffffff">
            <text id="title_2_1D_line_0" x="60.0" y="13.0" font-size="7.0" font-weight="normal"
                fill="#ffffff" text-anchor="middle" font-family="OpenSans">Personalize and
            </text>
            <text id="title_2_1D_line_1" x="60.0" y="21.4" font-size="7.0" font-weight="normal"
                fill="#ffffff" text-anchor="middle" font-family="OpenSans">Comfort
            </text>
        </g>
    </g>
</svg>

```

**Comment by BigBadaboom** [comment] 2023-08-30 23:05
Duplicate of #273?  Possible spam?

**Comment by Keyurshingala** [comment] 2023-08-31 10:38
description updated

**Comment by BigBadaboom** [comment] 2023-09-07 04:02
Updated, thanks. Reopening.

**Comment by BigBadaboom** [comment] 2023-09-07 04:10
![Screenshot in case Google Drive file goes away.](https://github.com/BigBadaboom/androidsvg/assets/840288/2b508bb2-efb2-4dfe-aa1b-3aefe481b038)

**Comment by BigBadaboom** [comment] 2023-09-07 04:21
The `viewBox` attribute tells the renderer what the bounds of the content of your SVG are.  You currently have specified "0, 0 500 500".  Which means that you are saying that the top left of the SVG content is at (0,0), and the width and height are both 500.

But your SVG has elements that have X and Y coordinates that are less than 0.  Also your SVG is smaller than 500x500.

A better `viewBox` that matches this SVG is `viewBox="-20 -90 230 180"`.

If this explanation does not make sense, I recommend reading a tutorial on the viewBox attribute.  There is also a good explanation in the SVG specification.

Hope this helps.

**Closed by BigBadaboom** 2023-09-07 04:21 UTC
Labels: question
