### ISSUE TITLE
stretching some svg file  crashes.

### ISSUE THREAD

**Issue by scau-beyondboy** [BigBadaboom/androidsvg#119] opened 2017-11-10 10:56 UTC
loading svg file with image element on some devices,once it is stretched,it crashes.

the text of svg file casuing crash:

```<svg width="506px" height="506px" viewBox="0 0 506 506" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 45.2 (43514) - http://www.bohemiancoding.com/sketch -->
    <title>img_noplaylist@3x</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-3" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Android锁屏播放页-（锁屏为空页）" transform="translate(-107.000000, -436.000000)">
            <image id="img_noplaylist" x="104" y="434" width="512" height="512" xlink:href="data:image/png;base64,........... omit"></image>
        </g>
    </g>
</svg>
```
crash information:
androidsvg version:1.2.1
device :SM-G900F;Android 5.0,level 21

crash report information:
`SIGSEGV(SEGV_MAPERR): #00 pc 001a1788 /system/lib/libskia.so (_Z31S32_opaque_D32_nofilter_DX_neonRK17SkBitmapProcStatePKjiPj+79) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #01 pc 000b6895 /system/lib/libskia.so (_ZN18SkBitmapProcShader23BitmapProcShaderContext9shadeSpanEiiPji+86) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #02 pc 000bf903 /system/lib/libskia.so (_ZN23SkARGB32_Shader_Blitter8blitRectEiiii+344) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #03 pc 000f2adb /system/lib/libskia.so [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #04 pc 000f2c25 /system/lib/libskia.so [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #05 pc 000f2cb1 /system/lib/libskia.so [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #06 pc 000f30eb /system/lib/libskia.so (_ZN6SkScan12AntiFillRectERK6SkRectPK8SkRegionP9SkBlitter+178) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #07 pc 000f3443 /system/lib/libskia.so (_ZN6SkScan12AntiFillRectERK6SkRectRK12SkRasterClipP9SkBlitter+14) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #08 pc 000cba83 /system/lib/libskia.so (_ZNK6SkDraw8drawRectERK6SkRectRK7SkPaint+298) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #09 pc 000ccb11 /system/lib/libskia.so (_ZNK6SkDraw10drawBitmapERK8SkBitmapRK8SkMatrixRK7SkPaint+322) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #10 pc 000c50ad /system/lib/libskia.so [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #11 pc 000c5195 /system/lib/libskia.so (_ZN8SkCanvas10drawBitmapERK8SkBitmapffPK7SkPaint+116) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #12 pc 000e4b47 /system/lib/libskia.so (_ZN17SkPicturePlayback4drawER8SkCanvasP21SkDrawPictureCallback+1182) [armeabi-v7a::a66e52245409b17a0468caae30b203d4] #13 pc 000b2517 /system/framework/arm/boot.oat (oatdata+726295) [armeabi::be9637244e74fadc148cbbb5094cb32c] java: android.graphics.Picture.draw(Picture.java:133) android.graphics.Canvas.drawPicture(Canvas.java:1879) android.graphics.drawable.PictureDrawable.draw(PictureDrawable.java:69) android.widget.ImageView.onDraw(ImageView.java:1187) android.view.View.draw(View.java:16060) android.view.View.buildDrawingCache(View.java:15286) android.view.View.updateDisplayListIfDirty(View.java:14972) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.updateDisplayListIfDirty(View.java:14986) android.view.View.getDisplayList(View.java:15014) android.view.View.draw(View.java:15781) android.view.ViewGroup.drawChild(ViewGroup.java:3677) android.view.ViewGroup.dispatchDraw(ViewGroup.java:3471) android.view.View.draw(View.java:16063) android.widget.FrameLayout.draw(FrameLayout.java:592) com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2916) android.view.View.updateDisplayListIfDirty(View.java:14991) android.view.View.getDisplayList(View.java:15014) android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275) android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281) android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320) android.view.ViewRootImpl.draw(ViewRootImpl.java:2741) android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2573) android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165) android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180) android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558) android.view.Choreographer$CallbackRecord.run(Choreographer.java:777) android.view.Choreographer.doCallbacks(Choreographer.java:590) android.view.Choreographer.doFrame(Choreographer.java:560) android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763) android.os.Handler.handleCallback(Handler.java:739) android.os.Handler.dispatchMessage(Handler.java:95) android.os.Looper.loop(Looper.java:145) android.app.ActivityThread.main(ActivityThread.java:5832) java.lang.reflect.Method.invoke(Native Method) java.lang.reflect.Method.invoke(Method.java:372) com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) java pending exception:`

when I replaced this using svg file without image element,,it did not crash.
the text of replaced-svg file:

```
<!-- Generator: Adobe Illustrator 16.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="512px" height="512px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
<path d="......... omit"/>
</svg>
```
so I guess that svg library is not support the svg with image element when needed to be stretched.

**Comment by BigBadaboom** [comment] 2017-11-10 13:48
This looks like a duplicate of #60 

Have you seen it on any devices other than ones running Android Lollipop?  Both of you were seeing this on 5.0. So it may have been a bug that has (hopefully) been fixed.  They found a workaround (rendering to an imatge and using an ImageView), that might be worth trying.

Other than the info in that report, and the linked Android and Skia bug reports, I don't have any suggestions. I think it is something out of my control.

**Comment by BigBadaboom** [comment] 2017-11-10 13:49
> once it is stretched,it crashes

What do you mean by that?  How were you stretching it?

**Comment by scau-beyondboy** [comment] 2017-11-12 14:37
this crash sample:[https://github.com/scau-beyondboy/SvgCrashDemo](url).
this crash can reproduce on SM-G900F using Android 5.0,but not crash in other devices.
change ImageView's width  and height attributes value to 300px(it's defined size less than it's origin size),it don't  crash,follow as figure:

![2017-11-12 at 10 33](https://user-images.githubusercontent.com/8970277/32699985-69ba818c-c7f9-11e7-9777-924bd87ae278.png).

so I guess once it is stretched,it crashes on SM-G900F when loading again.

**Comment by BigBadaboom** [comment] 2017-11-12 16:06
The only object in that SVG is a PNG bitmap image. There is really no point in it being an SVG.  It could just as easily be a normal PNG.

If you want to keep it as an SVG, then you should redraw it as a pure vector image.  There's a good chance, that if you do, that it will get of of your crash.

**Comment by scau-beyondboy** [comment] 2017-11-13 02:23
hi,how do redraw it as a pure vector image,thanks your help.

**Comment by BigBadaboom** [comment] 2017-11-13 02:50
You SVG was created in Sketch. It just contains a PNG with some  circles and curves.  Remove the PNG and draw the circles and curves using the tools in Sketch.

**Comment by scau-beyondboy** [comment] 2017-11-13 03:44
OK,thanks for your help.

**Closed** 2017-12-11 13:57 UTC
