### ISSUE TITLE
SVG not fully rendered

### ISSUE THREAD

**Issue by mueller-ma** [BigBadaboom/androidsvg#240] opened 2021-11-25 20:54 UTC
A user of openHAB, an app that uses this lib, claims that a SVG isn't rendered fully: https://github.com/openhab/openhab-android/issues/2749
I can reproduce this issue, but I don't see any log lines of androidsvg, e.g. some error messages or similar.

There are some parts missing, e.g. the cloud icons. According to http://bigbadaboom.github.io/androidsvg/svg_implementation_details.html they should be rendered as `<image>` tags with data urls are supported.

**Comment by BigBadaboom** [comment] 2021-11-26 13:57
[Issue240_meteogram.zip](https://github.com/BigBadaboom/androidsvg/files/7609144/Issue240_meteogram.zip)

**Comment by BigBadaboom** [comment] 2022-07-30 12:46
This is actually a duplicate of #236.

That bug is now fixed. So then so is this one :)

**Closed by BigBadaboom** 2022-07-30 12:46 UTC
Labels: bug, duplicate
